### ISSUE TITLE
Unable to load Iberian.Rdata

### ISSUE THREAD

**Issue by vjjan91** [SantanderMetGroup/notebooks#2]
Hello, I have working with this notebook - https://github.com/SantanderMetGroup/notebooks/blob/master/2019_downscaleR_GMD.Rmd

and all packages and their versions have been installed. Yet when I call  
load("Iberian.Rdata")

It says 'No such file or directory'. I have installed all packages successfully. 

Any suggestions?

**Comment by jbedia** [comment]
Hi, that code is not intended to be visible to the user (note the `echo=FALSE` option in the chunk options). It is better to use the compiled document (.html or .pdf), that should be fully reproducible.

**Comment by vjjan91** [comment]
Thanks, will try the same and keep you posted.
